language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database travelr_test;' -U postgres
- npm run migrate-test
- npm run seed-test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: LfLlqxAy4iQkoLTz8BUgEdmF4gIBoA8Nq07gWxhXVSGIw7mSdQZ3jkp10Law6+7wW8+U5ScDP2d4ChASVKYJhHc2Kysq/vdLNhh+9WruuWJDwMQPL+0jrDep3lof6dDHbOdjAdMIX3jLf61RxBWB9zF2ixg90Oq6fjEdaZbrwwKWTYKtovTb7jxjlwcsexTGJ+05QknO7kBEc0HJIrsn0bedTRIAfiHDDxYmx3E8IHHmRlkTxJ1/2Ebz5AWBWsLVEik5l73QAxZEmwpke9l0a/sbSXuRieo8saL99wMzAPb00EQcSqdEZOwlNz2zDgbNuuJCcSjoOVq4x+Bo9RJHK9GjW8gtw93AR+QY7WHtQUR1tf/wHoN+2ukiktkcmheJzf3+C98A+gRg+XNgKqRubqpQUdj/DV1ot576jBz8DQbxKpxX32v8a9hNRA9zIwNheGUTosrcxjUJdIDPOWnkJsDvdtECHAtsUk4V/EkZdFWz6FsGQinPE45vRbQ2GQpiJLIktDRZ8eGOVCJsCsuc/SDSRFMvFGmQ29qIGXywIPGVkyb0TbE6iTUAfXgGFyg3b4Ca2+CD3VOG1qDLmnKda1jts1McWj7L9IekNpeKinShstLC97dg9io3htb5dCp4FSjd/ExMQh4fsLSeALQBjGey4ehdqG/xmSlKgRzAeso=
  app: travelr-be
  run:
  - knex migrate:latest
  - knex seed:run
  skip_cleanup: true
