language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database travelr_test;' -U postgres
- npm run migrate-test
- npm run seed-test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 77icEjniWE5hzyFAcB5dkmKI1kp2Ehxn51ZQMfzcVjEd+PtJS6jShKYUgK/tONKQ1a9T9jAE52Uby05aK5vWSqVxGvME8br87SViAypIen1uRfTyuthHQ+HqSv8XhFxQoQQBv1SpANYfRkmzOlpYOHtB8jG2BhbpLUtS0ekXPuKk2AFMjOpFpnv4NXE0jyrKO63W7ieISHKS7Fjwi4R3C5enss0QA7ZZBfmGt6wED2Z02ncMMBRSN2Pz1DYcTs4JeXWoomQ1bGnV6DhnDDuYgGkf2aUWzveft8C/RH2WYSjH+RiuXMnmip9OxWBe7/yzwO2m3lMn/PQ3NmE04zoL3gkqYe43JohsRBuEN4VnC3mYsSSL2bzmQ6ujbhjZDRbKzOo2oIWifP8h6QQOGEU71Tnd1HrEQc8E0OLHETQsjBxJYlENDPO/xNJHlVt3rDPJz0+UfB4YAYkLsERcf+nAxiea3nMD6/6WEyUjN6VD1ZC9yuSidYa/nzGMuN7UxWY4fgYkF8cD636J8JL3SNZn7RVGmsl5fnUJwL0fcoPfaYpBwnwntT1BAziolROftKgVjwGKnaHAZ8I0VZxQUpYkVSu1Nxxcr5988HNveEUQus/oyofzKFuiYyv6HZlczVyenfPtsVxg2fLpfG5aN0c7jv30fKAOz93RnbGZjwFCk1Q=
  app: travelr-be
  run:
  - knex migrate:latest
  - knex seed:run
  skip_cleanup: true
